export const MUNICIPALITY_BARANGAYS: Record<string, string[]> = {
  Atok: ['Abiang', 'Caliking', 'Cattubo', 'Naguey', 'Paoay', 'Pasdong', 'Poblacion AT', 'Topdac'],
  'Baguio City': ['ABCR', 'AZCKO', 'Alfonso Tabora', 'Ambiong BC', 'Andres Bonifacio', 'Apugan-Loakan', 'Asin', 'Atok Trail', 'Aurora Hill Proper', 'BGH Compound', 'Bagong Lipunan', 'Bakakeng Central', 'Bakakeng Norte/Sur', 'Balsigan', 'Bayan Park Village', 'Brookside', 'Brookspoint', 'Cabinet Hill - Teachers Camp', 'Camdas', 'Camp 7', 'Camp 8', 'Camp Henry I. Allen', 'Campo Filipino', 'City Camp Central', 'City Camp Proper', 'Country Club Village', 'Cresencia Village', 'DPS Compound', 'Dizon Subdivision', 'Dominican Hill - Mirador', 'Dontogan', 'East Bayan Park', 'East Modern Site', 'East Quirino Hill', 'Engineers Hill', 'Fairview', 'Ferdinand', 'Fort del Pilar', 'Gabriela Silang', 'General Emilio F. Aguinaldo', 'Gibraltar', 'Greenwater Village', 'Guisad Central', 'Guisad Surong', 'Happy Hallow', 'Happy Homes-Lucban', 'Harrison-Claudio Carantes', 'Hillside', 'Holy Ghost Extension', 'Holy Ghost Proper', 'Honeymoon - Holy Ghost', 'Imelda R. Marcos', 'Imelda Village', 'Irisan', 'Kabayanihan', 'Kagitingan', 'Kayang - Hilltop', 'Kayang Extension', 'Kias', 'Legarda-Burnham-Kisad', 'Liwanag-Loakan', 'Loakan Proper', 'Lopez Jaena', 'Lourdes Subdivision Extension', 'Lourdes Subdivision Proper', 'Lower Dagsian', 'Lower General Luna', 'Lower Lourdes Subdivision', 'Lower Magsaysay', 'Lower Quirino Hill', 'Lower Rock Quarry', 'Lualhati Village', 'Lucnab', 'MRR Queen of Peace', 'Magsaysay Private Road', 'Malcolm Square-Perfecto', 'Manuel A. Roxas', 'Marcoville', 'Middle Quezon Hill', 'Middle Quirino Hill', 'Middle Rock Quarry', 'Military Cut-Off', 'Mines View Park', 'New Lucban', 'North Central Aurora Hill', 'North Sanitary Camp', 'Outlook Drive', 'Pacdal', 'Padre Burgos', 'Padre Zamora', 'Palma - Urbano', 'Phil-Am Compound', 'Pinget', 'Pinsao Pilot Project', 'Pinsao Proper', 'Poliwes', 'Pucsusan', 'Quezon Hill Proper', 'Rizal Monument', 'SLU-SVP Housing', 'Salud Mitra', 'San Antonio Village', 'San Luis Village', 'San Roque Village', 'San Vicente', 'Scout Barrio', 'Session Road', 'South Central Aurora Hill', 'South Drive', 'South Sanitary Camp', 'St. Joseph Village', 'Sta. Scholastica', 'Sto. Nino-Slaughter Compound', 'Sto. Rosario Valley', 'Sto. Tomas Proper', 'Sto. Tomas School Area', 'Teodora Alonzo', 'Trancoville', 'Upper Dagsian', 'Upper General Luna', 'Upper Magsaysay', 'Upper Market Subdivision', 'Upper Quezon Hill', 'Upper Quirino Magsaysay', 'Upper Rock Quarry', 'Victoria Village', 'West Bayan Park', 'West Modern Site', 'West Quirino Hill'],
  Bakun: ['Ampusongan', 'Bagu', 'Central BN', 'Dalipey', 'Gambang', 'Kayapa', 'Sinacbat'],
  Bokod: ['Ambuclao', 'Bila', 'Bobok-Bisal', 'Daclan BD', 'Ekip', 'Karao', 'Kawal', 'Nawal', 'Pito', 'Poblacion BD', 'Tikey'],
  Buguias: ['Abatan', 'Amgaleyguey', 'Amlimay', 'Baculongan Norte', 'Baculongan Sur', 'Bangao', 'Buyacaoan', 'Calamagan', 'Catlubong', 'Lengaoan', 'Loo', 'Natubleng', 'Poblacion BS', 'Sebang'],
  Itogon: ['Ampucao', 'Dalupirip', 'Gumatdang', 'Loacan', 'Poblacion IT', 'Tinongdan', 'Tuding', 'Ucab', 'Virac'],
  Kabayan: ['Adaoay', 'Anchokey', 'Ballay', 'Bashoy', 'Batan', 'Duacan', 'Eddet', 'Gusaran', 'Kabayan Barrio', 'Lusod', 'Pacso', 'Poblacion KB', 'Tawangan'],
  Kapangan: ['Balakbak', 'Beleng-Belis', 'Boklaoan', 'Cayapes', 'Cuba', 'Datakan', 'Gadang', 'Gaswiling', 'Labueg', 'Paykek', 'Poblacion Central', 'Pongayan', 'Pudong', 'Sagubo', 'Taba-ao'],
  Kibungan: ['Badeo', 'Lubo', 'Madaymen', 'Palina', 'Poblacion KN', 'Sagpat', 'Tacadang'],
  'La Trinidad': ['Alapang', 'Alno', 'Ambiong LT', 'Bahong', 'Balili LT', 'Beckel', 'Betag', 'Bineng', 'Cruz', 'Lubas', 'Pico', 'Poblacion LT', 'Puguis', 'Shilan', 'Tawang', 'Wangal'],
  'La Union': ['Aringay'],
  Mankayan: ['Balili MN', 'Bedbed', 'Bulalacao', 'Cabiten', 'Colalo', 'Guinaoang', 'Paco', 'Poblacion MN', 'Sapid', 'Suyoc', 'Tabio', 'Taneg'],
  'Outside Franchise Area': ['Outside Benguet'],
  Pangasinan: ['Sison'],
  Sablan: ['Bagong', 'Balluay', 'Banangan', 'Banengbeng', 'Bayabas', 'Kamog', 'Pappa', 'Poblacion SB'],
  Tuba: ['Ansagan', 'Camp 1', 'Camp 3', 'Camp 4', 'Nangalisan', 'Poblacion TB', 'San Pascual', 'Tabaan Norte', 'Tabaan Sur', 'Tadiangan', 'Taloy Norte', 'Taloy Sur', 'Twin Peaks'],
  Tublay: ['Ambassador', 'Ambongdolan', 'Ba-ayan', 'Basil', 'Caponga', 'Daclan TY', 'Tublay Central', 'Tuel'],
};

export const MUNICIPALITIES = Object.keys(MUNICIPALITY_BARANGAYS).sort((a, b) => a.localeCompare(b));
