import { useEffect, useMemo, useRef, useState } from 'react';
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, startOfMonth, startOfWeek, subMonths } from 'date-fns';
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/input';
import { cn } from '@/lib/utils';

export function DateRangePicker({ startDate, endDate, onChange, label = 'Date / Date Range', required = false, placement = 'bottom' }: { startDate: string; endDate: string; onChange: (startDate: string, endDate: string) => void; label?: string; required?: boolean; placement?: 'top' | 'bottom' }) {
  const [open, setOpen] = useState(false);
  const [selectingEnd, setSelectingEnd] = useState(false);
  const [month, setMonth] = useState(() => new Date(`${startDate || endDate || format(new Date(), 'yyyy-MM-dd')}T00:00:00`));
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const close = (event: PointerEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, [open]);
  const days = useMemo(() => eachDayOfInterval({ start: startOfWeek(startOfMonth(month)), end: endOfWeek(endOfMonth(month)) }), [month]);
  const labelText = !endDate ? 'Select tentative date or range' : startDate && startDate !== endDate ? `${format(new Date(`${startDate}T00:00:00`), 'MMM d, yyyy')} – ${format(new Date(`${endDate}T00:00:00`), 'MMM d, yyyy')}` : format(new Date(`${endDate}T00:00:00`), 'MMM d, yyyy');
  function pick(day: Date) { const value = format(day, 'yyyy-MM-dd'); if (!selectingEnd) { onChange(value, value); setSelectingEnd(true); setMonth(day); return; } const first = new Date(`${startDate || endDate}T00:00:00`); if (day < first) onChange(value, startDate || endDate); else onChange(startDate || endDate, value); setSelectingEnd(false); setOpen(false); }
  return <div ref={ref} className="relative sm:col-span-2"><Label required={required}>{label}</Label><button type="button" onClick={() => { setOpen((value) => !value); setSelectingEnd(false); }} className="mt-1 flex h-10 w-full items-center justify-between rounded-md border border-slate-300 bg-surface px-3 text-left text-sm font-medium text-slate-800 shadow-sm hover:border-brand-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"><span>{labelText}</span><span className="flex items-center gap-2 text-xs text-slate-400"><CalendarDays className="h-4 w-4" />{startDate && startDate !== endDate ? 'Range' : endDate ? '1 day' : ''}</span></button>{open && <div className={cn('absolute z-[100] w-full max-w-md rounded-lg border border-slate-200 bg-surface p-3 shadow-2xl', placement === 'top' ? 'bottom-full mb-2' : 'mt-2')}><div className="mb-2 flex items-center justify-between"><Button type="button" variant="outline" size="icon" onClick={() => setMonth((value) => subMonths(value, 1))}><ChevronLeft className="h-4 w-4" /></Button><div className="text-center"><p className="text-sm font-semibold">{format(month, 'MMMM yyyy')}</p><p className="text-[11px] text-slate-500">{selectingEnd ? 'Select an end date, or Done for one day.' : 'Select a tentative start date.'}</p></div><Button type="button" variant="outline" size="icon" onClick={() => setMonth((value) => addMonths(value, 1))}><ChevronRight className="h-4 w-4" /></Button></div><div className="grid grid-cols-7 text-center text-[10px] font-semibold uppercase text-slate-500">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((value) => <span key={value} className="py-1">{value}</span>)}</div><div className="grid grid-cols-7 gap-1">{days.map((day) => { const value = format(day, 'yyyy-MM-dd'); const inRange = Boolean(startDate && endDate && value >= startDate && value <= endDate); const edge = value === startDate || value === endDate; return <button key={value} type="button" onClick={() => pick(day)} className={cn('h-8 rounded-md text-xs font-medium hover:bg-brand-50', !isSameMonth(day, month) && 'text-slate-300', inRange && 'bg-brand-50 text-brand-700', edge && 'bg-brand-600 text-white hover:bg-brand-600')}>{format(day, 'd')}</button>; })}</div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><p className="text-xs text-slate-500">Pick once for one day or choose a second date for a range.</p><Button type="button" size="sm" onClick={() => { if (startDate || endDate) onChange(startDate || endDate, startDate || endDate); setSelectingEnd(false); setOpen(false); }}>Done</Button></div></div>}</div>;
}
