import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { ArrowUpRight, Circle, MessageSquare, MousePointer2, Redo2, Square, Trash2 } from 'lucide-react';

export type ModelAnnotation = { id: string; type: 'circle' | 'rectangle' | 'callout' | 'arrow'; color: string; x: number; y: number; width: number; height: number; text?: string };
export type VehicleModelViewerHandle = { captureSnapshot: () => Promise<string> };

export const VehicleModelViewer = forwardRef<VehicleModelViewerHandle, { dataUrl: string; name: string; annotations: ModelAnnotation[]; onAnnotationsChange: (items: ModelAnnotation[]) => void }>(function VehicleModelViewer({ dataUrl, name, annotations, onAnnotationsChange }, ref) {
  const hostRef = useRef<HTMLDivElement>(null); const svgRef = useRef<SVGSVGElement>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [tool, setTool] = useState<'navigate' | ModelAnnotation['type']>('navigate'); const [color, setColor] = useState('#ef4444'); const [draft, setDraft] = useState<ModelAnnotation | null>(null);
  const [calloutText, setCalloutText] = useState('Finding');

  useImperativeHandle(ref, () => ({ captureSnapshot: async () => {
    const canvas = hostRef.current?.querySelector('canvas'); const svg = svgRef.current;
    if (!canvas || !svg) throw new Error('The 3D viewer is not ready.');
    const output = document.createElement('canvas'); output.width = canvas.width; output.height = canvas.height;
    const context = output.getContext('2d'); if (!context) throw new Error('Unable to create snapshot.'); context.drawImage(canvas, 0, 0);
    const overlay = new Image(); const markup = new XMLSerializer().serializeToString(svg);
    await new Promise<void>((resolve, reject) => { overlay.onload = () => resolve(); overlay.onerror = () => reject(new Error('Unable to render annotations.')); overlay.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(markup)}`; });
    context.drawImage(overlay, 0, 0, output.width, output.height); return output.toDataURL('image/png');
  } }));

  useEffect(() => {
    const host = hostRef.current; if (!host) return; setLoading(true); setError('');
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0xf1f5f9); const camera = new THREE.PerspectiveCamera(40, 1, .01, 10000);
    const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true }); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); host.appendChild(renderer.domElement);
    const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.screenSpacePanning = true;
    scene.add(new THREE.HemisphereLight(0xffffff, 0x475569, 2.5)); const light = new THREE.DirectionalLight(0xffffff, 3); light.position.set(4, 6, 5); scene.add(light);
    let model: THREE.Object3D | undefined;
    new GLTFLoader().load(dataUrl, (gltf) => { model = gltf.scene; scene.add(model); const box = new THREE.Box3().setFromObject(model); const size = box.getSize(new THREE.Vector3()); const center = box.getCenter(new THREE.Vector3()); const radius = Math.max(size.x, size.y, size.z) || 1; model.position.sub(center); camera.near = Math.max(radius / 100, .01); camera.far = radius * 100; camera.position.set(radius * 1.5, radius * .9, radius * 1.5); camera.updateProjectionMatrix(); controls.target.set(0, 0, 0); controls.update(); setLoading(false); }, undefined, () => { setError('The attached GLB could not be displayed.'); setLoading(false); });
    const resize = () => { const width = Math.max(host.clientWidth, 1), height = Math.max(host.clientHeight, 1); renderer.setSize(width, height, false); camera.aspect = width / height; camera.updateProjectionMatrix(); }; const observer = new ResizeObserver(resize); observer.observe(host); resize();
    let frame = 0; const render = () => { controls.update(); renderer.render(scene, camera); frame = requestAnimationFrame(render); }; render();
    return () => { cancelAnimationFrame(frame); observer.disconnect(); controls.dispose(); model?.traverse((child) => { if (child instanceof THREE.Mesh) { child.geometry.dispose(); (Array.isArray(child.material) ? child.material : [child.material]).forEach((material) => material.dispose()); } }); renderer.dispose(); renderer.domElement.remove(); };
  }, [dataUrl]);

  const point = (event: ReactPointerEvent<SVGSVGElement>) => { const box = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - box.left) / box.width * 100, y: (event.clientY - box.top) / box.height * 100 }; };
  const down = (event: ReactPointerEvent<SVGSVGElement>) => { if (tool === 'navigate') return; const start = point(event); if (tool === 'callout') { onAnnotationsChange([...annotations, { id: `ANN-${Date.now()}`, type: tool, color, ...start, width: 0, height: 0, text: calloutText.trim() || 'Finding' }]); return; } event.currentTarget.setPointerCapture(event.pointerId); setDraft({ id: `ANN-${Date.now()}`, type: tool, color, ...start, width: 0, height: 0 }); };
  const move = (event: ReactPointerEvent<SVGSVGElement>) => { if (!draft) return; const end = point(event); setDraft({ ...draft, width: end.x - draft.x, height: end.y - draft.y }); };
  const up = () => { if (!draft) return; if (Math.abs(draft.width) > 1 && Math.abs(draft.height) > 1) onAnnotationsChange([...annotations, draft]); setDraft(null); }; const visible = draft ? [...annotations, draft] : annotations;
  return <div className="space-y-2"><div className="flex flex-wrap items-center gap-1 rounded-lg border bg-slate-50 p-1.5"><Tool label="Navigate" active={tool === 'navigate'} onClick={() => setTool('navigate')} icon={MousePointer2}/><Tool label="Circle" active={tool === 'circle'} onClick={() => setTool('circle')} icon={Circle}/><Tool label="Rectangle" active={tool === 'rectangle'} onClick={() => setTool('rectangle')} icon={Square}/><Tool label="Arrow" active={tool === 'arrow'} onClick={() => setTool('arrow')} icon={ArrowUpRight}/><Tool label="Callout" active={tool === 'callout'} onClick={() => setTool('callout')} icon={MessageSquare}/>{tool === 'callout' && <input value={calloutText} onChange={(event) => setCalloutText(event.target.value)} placeholder="Callout text" style={{ color: '#000000', WebkitTextFillColor: '#000000' }} className="h-7 min-w-32 flex-1 rounded border border-slate-400 bg-white px-2 text-xs caret-black placeholder:!text-slate-600"/>}<label className="ml-1 flex items-center gap-1 text-xs font-medium">Color<input type="color" value={color} onChange={(event) => setColor(event.target.value)} className="h-7 w-9" /></label><button type="button" className="ml-auto p-1.5 disabled:opacity-30" disabled={!annotations.length} onClick={() => onAnnotationsChange(annotations.slice(0, -1))} title="Undo"><Redo2 className="h-4 w-4 -scale-x-100" /></button><button type="button" className="p-1.5 text-red-600 disabled:opacity-30" disabled={!annotations.length} onClick={() => onAnnotationsChange([])} title="Clear"><Trash2 className="h-4 w-4" /></button></div><div className="relative overflow-hidden rounded-xl border bg-slate-100"><div ref={hostRef} className="h-[360px] w-full" aria-label={`Interactive 3D model of ${name}`} /><svg ref={svgRef} viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={down} onPointerMove={move} onPointerUp={up} className={`absolute inset-0 h-full w-full ${tool === 'navigate' ? 'pointer-events-none' : 'cursor-crosshair'}`}><defs><marker id="vehicle-annotation-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 z" fill="context-stroke" /></marker></defs>{visible.map((item) => <Shape key={item.id} item={item}/>)}</svg>{loading && <div className="absolute inset-0 grid place-items-center bg-slate-100/80 text-sm">Loading 3D vehicle…</div>}{error && <div className="absolute inset-0 grid place-items-center p-8 text-center text-sm text-red-700">{error}</div>}<div className="pointer-events-none absolute bottom-2 left-2 rounded bg-slate-900/70 px-2 py-1 text-[10px] text-white">{tool === 'navigate' ? 'Drag to rotate · Scroll to zoom · Right-drag to pan' : tool === 'callout' ? 'Enter text above, then click to place the callout' : `Drag to draw an ${tool}`}</div></div></div>;
});

function Shape({ item }: { item: ModelAnnotation }) { const x = item.width < 0 ? item.x + item.width : item.x, y = item.height < 0 ? item.y + item.height : item.y, width = Math.abs(item.width), height = Math.abs(item.height); if (item.type === 'circle') return <ellipse cx={x + width / 2} cy={y + height / 2} rx={width / 2} ry={height / 2} fill={`${item.color}22`} stroke={item.color} strokeWidth=".7"/>; if (item.type === 'rectangle') return <rect x={x} y={y} width={width} height={height} fill={`${item.color}22`} stroke={item.color} strokeWidth=".7"/>; if (item.type === 'arrow') return <line x1={item.x} y1={item.y} x2={item.x + item.width} y2={item.y + item.height} stroke={item.color} strokeWidth="1" markerEnd="url(#vehicle-annotation-arrow)"/>; return <g><circle cx={item.x} cy={item.y} r="1.3" fill={item.color}/><line x1={item.x} y1={item.y} x2={Math.min(item.x + 10, 88)} y2={Math.max(item.y - 8, 8)} stroke={item.color} strokeWidth=".6"/><rect x={Math.min(item.x + 9, 72)} y={Math.max(item.y - 12, 2)} width="25" height="7" rx="1" fill="white" stroke={item.color}/><text x={Math.min(item.x + 10, 73)} y={Math.max(item.y - 7.5, 6.5)} fill={item.color} fontSize="2.5">{item.text}</text></g>; }
function Tool({ label, active, onClick, icon: Icon }: { label: string; active: boolean; onClick: () => void; icon: typeof Circle }) { return <button type="button" onClick={onClick} className={`inline-flex items-center gap-1 rounded px-2 py-1.5 text-xs font-medium ${active ? 'bg-brand-600 text-white' : 'hover:bg-slate-200'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>; }
