import { useEffect, useMemo, useState } from 'react';
import { BarChart3, ChevronDown, ChevronRight, FolderTree, Pencil, Plus } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ConfirmDialog, Dialog } from '@/components/ui/dialog';
import { Checkbox, Input, Label, Select, Textarea } from '@/components/ui/input';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';
import { deleteMemberProgram, fetchMemberPrograms, saveMemberProgram, type MemberProgram, type MemberProgramInput, type MemberProgramStatus } from '@/lib/api';

const STATUSES: MemberProgramStatus[] = ['Planned', 'Ongoing', 'Completed', 'On Hold', 'Cancelled'];
const STATUS_COLORS: Record<MemberProgramStatus, string> = { Planned: 'bg-blue-500', Ongoing: 'bg-emerald-500', Completed: 'bg-slate-500', 'On Hold': 'bg-amber-500', Cancelled: 'bg-red-500' };
const today = new Date().toISOString().slice(0, 10);
const emptyForm: MemberProgramInput = { parentId: null, name: '', description: '', startDate: today, endDate: today, status: 'Planned' };

function ProgramBranch({ program, programs, depth, onAddChild, onEdit }: { program: MemberProgram; programs: MemberProgram[]; depth: number; onAddChild: (program: MemberProgram) => void; onEdit: (program: MemberProgram) => void }) {
  const [expanded, setExpanded] = useState(true);
  const children = programs.filter((item) => item.parentId === program.id);
  return <div className={depth ? 'ml-4 border-l border-slate-200 pl-4' : ''}>
    <div className="rounded-lg border border-slate-200 bg-surface p-3">
      <div className="flex flex-wrap items-start justify-between gap-3"><button type="button" className="flex min-w-0 items-center gap-2 text-left" onClick={() => setExpanded((value) => !value)}>{children.length ? expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" /> : <span className="w-4" />}<FolderTree className="h-4 w-4 text-brand-600" /><span className="font-semibold text-slate-900">{program.name}</span></button><div className="flex items-center gap-2"><Badge>{program.status}</Badge><Button size="sm" variant="outline" onClick={() => onAddChild(program)}><Plus className="h-3.5 w-3.5" /> Sub-program</Button><Button size="icon" variant="ghost" aria-label={`Edit ${program.name}`} onClick={() => onEdit(program)}><Pencil className="h-4 w-4" /></Button></div></div>
      <div className="mt-2 flex flex-wrap gap-3 text-xs text-slate-500"><span>{program.startDate === program.endDate ? program.startDate : `${program.startDate} – ${program.endDate}`}</span>{program.description && <span>{program.description}</span>}</div>
    </div>
    {expanded && children.length > 0 && <div className="mt-2 space-y-2">{children.map((child) => <ProgramBranch key={child.id} program={child} programs={programs} depth={depth + 1} onAddChild={onAddChild} onEdit={onEdit} />)}</div>}
  </div>;
}

export function MemberProgramsPrograms() {
  const { token } = useAuth(); const { toast } = useToast();
  const [programs, setPrograms] = useState<MemberProgram[]>([]); const [open, setOpen] = useState(false); const [summaryOpen, setSummaryOpen] = useState(false); const [editing, setEditing] = useState<MemberProgram | null>(null); const [form, setForm] = useState<MemberProgramInput>(emptyForm); const [singleDay, setSingleDay] = useState(true); const [saving, setSaving] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false);
  async function load() { if (!token) return; try { setPrograms(await fetchMemberPrograms(token)); } catch (error) { toast({ kind: 'error', title: 'Programs not loaded', description: error instanceof Error ? error.message : 'Please try again.' }); } }
  useEffect(() => { void load(); }, [token]);
  function add(parent: MemberProgram | null = null) { setEditing(null); setForm({ ...emptyForm, parentId: parent?.id ?? null }); setSingleDay(true); setOpen(true); }
  function edit(program: MemberProgram) { setEditing(program); setForm({ parentId: program.parentId, name: program.name, description: program.description, startDate: program.startDate, endDate: program.endDate, status: program.status }); setSingleDay(program.startDate === program.endDate); setOpen(true); }
  async function save() { if (!token || !form.name.trim() || !form.startDate || !form.endDate || form.endDate < form.startDate) return; setSaving(true); try { await saveMemberProgram(token, { ...form, name: form.name.trim(), description: form.description.trim(), endDate: singleDay ? form.startDate : form.endDate }, editing?.id); await load(); setOpen(false); toast({ kind: 'success', title: editing ? 'Program updated' : 'Program added', description: 'The tentative schedule was saved in the Programs database.' }); } catch (error) { toast({ kind: 'error', title: 'Program not saved', description: error instanceof Error ? error.message : 'Please try again.' }); } finally { setSaving(false); } }
  async function remove() { if (!token || !editing) return; setSaving(true); try { await deleteMemberProgram(token, editing.id); await load(); setDeleteOpen(false); setOpen(false); toast({ kind: 'success', title: 'Program deleted', description: 'The program and its child programs were removed.' }); } catch (error) { toast({ kind: 'error', title: 'Program not deleted', description: error instanceof Error ? error.message : 'Please try again.' }); } finally { setSaving(false); } }
  const roots = programs.filter((item) => !item.parentId);
  const range = useMemo(() => { if (!programs.length) return { start: new Date(), days: 1 }; const dates = programs.flatMap((item) => [new Date(`${item.startDate}T00:00:00`), new Date(`${item.endDate}T00:00:00`)]); const start = new Date(Math.min(...dates.map(Number))); const end = new Date(Math.max(...dates.map(Number))); return { start, days: Math.max(1, Math.round((Number(end) - Number(start)) / 86400000) + 1) }; }, [programs]);
  return <>
    <Card><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle>Programs</CardTitle><p className="mt-1 text-sm text-slate-500">Non-recurring parent and child programs with tentative schedules.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setSummaryOpen(true)}><BarChart3 className="h-4 w-4" /> Summary</Button><Button onClick={() => add()}><Plus className="h-4 w-4" /> Add Program</Button></div></CardHeader><CardContent>{roots.length ? <div className="space-y-3">{roots.map((program) => <ProgramBranch key={program.id} program={program} programs={programs} depth={0} onAddChild={add} onEdit={edit} />)}</div> : <div className="flex min-h-48 flex-col items-center justify-center rounded-lg border border-dashed border-slate-300 text-center"><FolderTree className="h-9 w-9 text-slate-400" /><p className="mt-3 font-medium text-slate-700">No programs yet</p><p className="mt-1 text-sm text-slate-500">Add a program and its tentative schedule.</p></div>}</CardContent></Card>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} title={editing ? 'Edit Program' : form.parentId ? 'Add Sub-program' : 'Add Program'} description="Define this non-recurring program and its tentative schedule." size="md" footer={<>{editing && <Button variant="destructive" disabled={saving} onClick={() => setDeleteOpen(true)}>Delete</Button>}<span className="flex-1" /><Button variant="outline" disabled={saving} onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving || !form.name.trim() || !form.startDate || !form.endDate || form.endDate < form.startDate} onClick={() => void save()}>{saving ? 'Saving…' : 'Save Program'}</Button></>}><div className="space-y-4"><div><Label required>Name</Label><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} autoFocus /></div><div><Label>Description</Label><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div><div><Label>Status</Label><Select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as MemberProgramStatus })}>{STATUSES.map((status) => <option key={status}>{status}</option>)}</Select></div><label className="flex items-center gap-2 text-sm text-slate-700"><Checkbox checked={singleDay} onChange={(event) => { setSingleDay(event.target.checked); if (event.target.checked) setForm({ ...form, endDate: form.startDate }); }} />Single-day program</label><div className="grid grid-cols-2 gap-3"><div><Label required>{singleDay ? 'Tentative Date' : 'Start Date'}</Label><Input type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value, endDate: singleDay ? event.target.value : form.endDate })} /></div>{!singleDay && <div><Label required>End Date</Label><Input type="date" min={form.startDate} value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></div>}</div>{!singleDay && form.endDate < form.startDate && <p className="text-xs text-red-600">End Date must be on or after Start Date.</p>}</div></Dialog>
    <Dialog open={summaryOpen} onClose={() => setSummaryOpen(false)} title="Programs Schedule Summary" description="Tentative Gantt chart for all parent and child programs." size="xl" footer={<Button variant="outline" onClick={() => setSummaryOpen(false)}>Close</Button>}><div className="space-y-2 overflow-x-auto">{programs.length ? programs.map((program) => { const start = Math.round((Number(new Date(`${program.startDate}T00:00:00`)) - Number(range.start)) / 86400000); const duration = Math.max(1, Math.round((Number(new Date(`${program.endDate}T00:00:00`)) - Number(new Date(`${program.startDate}T00:00:00`))) / 86400000) + 1); return <div key={program.id} className="grid min-w-[760px] grid-cols-[220px_1fr] items-center gap-3"><div><p className="truncate text-sm font-medium text-slate-800">{program.name}</p><p className="text-xs text-slate-500">{program.startDate}{program.startDate !== program.endDate ? ` – ${program.endDate}` : ''}</p></div><div className="relative h-9 rounded bg-slate-100"><div className={`absolute top-1 h-7 rounded px-2 text-xs leading-7 text-white ${STATUS_COLORS[program.status]}`} style={{ left: `${(start / range.days) * 100}%`, width: `${Math.max(2, (duration / range.days) * 100)}%` }}><span className="whitespace-nowrap">{program.status}</span></div></div></div>; }) : <p className="py-12 text-center text-sm text-slate-500">No scheduled programs to summarize.</p>}</div></Dialog>
    <ConfirmDialog open={deleteOpen} onClose={() => setDeleteOpen(false)} onConfirm={() => void remove()} title="Delete program?" description={`Delete “${editing?.name ?? ''}” and all of its child programs?`} confirmLabel="Delete" destructive />
  </>;
}
