import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { ChevronDown, ChevronRight, Download, ExternalLink, File, Folder, FolderOpen, FolderPlus, Grid2X2, HardDrive, Link2, List, MoreVertical, Plus, Search, Upload, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog } from '@/components/ui/dialog';
import { Input, Label } from '@/components/ui/input';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';
import { createBfmProjectFolder, createBfmProjectLink, downloadBfmProjectFile, fetchBfmProjectResources, uploadBfmProjectFile, type BfmProject, type BfmProjectFolder, type BfmProjectResource } from '@/lib/api';

type Composer = 'folder' | 'link' | null;

export function BfmProjectDocumentsDialog({ project, open, onClose }: { project: BfmProject | null; open: boolean; onClose: () => void }) {
  const { token } = useAuth(); const { toast } = useToast();
  const [folders, setFolders] = useState<BfmProjectFolder[]>([]); const [resources, setResources] = useState<BfmProjectResource[]>([]);
  const [currentFolder, setCurrentFolder] = useState(''); const [query, setQuery] = useState(''); const [grid, setGrid] = useState(true); const [composer, setComposer] = useState<Composer>(null);
  const [folderName, setFolderName] = useState(''); const [linkName, setLinkName] = useState(''); const [linkUrl, setLinkUrl] = useState(''); const [newMenu, setNewMenu] = useState(false);
  const [saving, setSaving] = useState(false); const filesRef = useRef<HTMLInputElement>(null); const folderRef = useRef<HTMLInputElement>(null);

  async function load() { if (!token || !project) return; const result = await fetchBfmProjectResources(token, project.id); setFolders(result.folders); setResources(result.resources); }
  useEffect(() => { if (open && project) { setCurrentFolder(''); setQuery(''); setComposer(null); void load().catch((error) => toast({ kind: 'error', title: 'Unable to load related documents', description: error instanceof Error ? error.message : 'Please try again.' })); } }, [open, project?.id, token]);
  async function createFolder() { if (!token || !project || !folderName.trim()) return; setSaving(true); try { await createBfmProjectFolder(token, project.id, folderName.trim()); setFolderName(''); setComposer(null); await load(); } catch (error) { toast({ kind: 'error', title: 'Folder was not created', description: error instanceof Error ? error.message : 'Please try again.' }); } finally { setSaving(false); } }
  async function addLink() { if (!token || !project || !linkName.trim() || !linkUrl.trim()) return; setSaving(true); try { await createBfmProjectLink(token, project.id, { name: linkName.trim(), url: linkUrl.trim(), folderId: currentFolder || undefined }); setLinkName(''); setLinkUrl(''); setComposer(null); await load(); } catch (error) { toast({ kind: 'error', title: 'Link was not added', description: error instanceof Error ? error.message : 'Please try again.' }); } finally { setSaving(false); } }
  async function uploadFiles(event: ChangeEvent<HTMLInputElement>, directFolder = false) {
    if (!token || !project || !event.target.files?.length) return; setSaving(true);
    try { for (const file of Array.from(event.target.files)) { const relativePath = (file as File & { webkitRelativePath?: string }).webkitRelativePath || ''; const rootFolder = directFolder && relativePath ? relativePath.split('/')[0] : folders.find((folder) => folder.id === currentFolder)?.name; await uploadBfmProjectFile(token, project.id, file, { folderName: rootFolder, relativePath }); } await load(); toast({ kind: 'success', title: event.target.files.length === 1 ? 'File uploaded' : `${event.target.files.length} files uploaded` }); }
    catch (error) { toast({ kind: 'error', title: 'Upload was not completed', description: error instanceof Error ? error.message : 'Please try again.' }); }
    finally { event.target.value = ''; setSaving(false); }
  }
  const currentFolderName = folders.find((folder) => folder.id === currentFolder)?.name; const term = query.trim().toLowerCase();
  const visibleFolders = currentFolder ? [] : folders.filter((folder) => !term || folder.name.toLowerCase().includes(term));
  const visibleResources = resources.filter((resource) => term ? resource.name.toLowerCase().includes(term) : (resource.folderId || '') === currentFolder);
  const openResource = (resource: BfmProjectResource) => resource.type === 'link' ? window.open(resource.url, '_blank', 'noopener,noreferrer') : token && void downloadBfmProjectFile(token, resource);

  return <Dialog open={open && Boolean(project)} onClose={() => { if (!saving) onClose(); }} title={`Related Documents — ${project?.title || ''}`} description="Project files, folders, and connected document links." size="xl" footer={<Button variant="outline" disabled={saving} onClick={onClose}>Close</Button>}>
    <div className="-m-6 flex h-[620px] min-h-0 max-w-[calc(100%+3rem)] overflow-hidden bg-surface text-slate-800">
      <aside className="w-52 shrink-0 border-r border-slate-200 bg-canvas p-3">
        <div className="relative mb-4"><Button className="w-full justify-start rounded-xl bg-surface text-slate-800 shadow-sm ring-1 ring-slate-200 hover:bg-slate-100" onClick={() => setNewMenu((value) => !value)}><Plus className="h-5 w-5 text-brand-600" /> New <ChevronDown className="ml-auto h-4 w-4" /></Button>{newMenu && <div className="absolute left-0 right-0 top-11 z-20 overflow-hidden rounded-xl border border-slate-200 bg-surface py-1 shadow-xl"><button className="flex w-full items-center gap-3 px-3 py-2 text-sm hover:bg-slate-100" onClick={() => { setComposer('folder'); setNewMenu(false); }}><FolderPlus className="h-4 w-4" /> New folder</button><button className="flex w-full items-center gap-3 px-3 py-2 text-sm hover:bg-slate-100" onClick={() => { filesRef.current?.click(); setNewMenu(false); }}><Upload className="h-4 w-4" /> File upload</button><button className="flex w-full items-center gap-3 px-3 py-2 text-sm hover:bg-slate-100" onClick={() => { folderRef.current?.click(); setNewMenu(false); }}><FolderOpen className="h-4 w-4" /> Folder upload</button><button className="flex w-full items-center gap-3 px-3 py-2 text-sm hover:bg-slate-100" onClick={() => { setComposer('link'); setNewMenu(false); }}><Link2 className="h-4 w-4" /> Add link</button></div>}</div>
        <button className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium ${!currentFolder ? 'bg-brand-50 text-brand-700' : 'hover:bg-slate-100'}`} onClick={() => setCurrentFolder('')}><HardDrive className="h-4 w-4" /> My Drive</button>
        <p className="mb-1 mt-4 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400">Folders</p><div className="space-y-0.5 overflow-y-auto">{folders.map((folder) => <button key={folder.id} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm ${currentFolder === folder.id ? 'bg-brand-50 font-medium text-brand-700' : 'hover:bg-slate-100'}`} onClick={() => setCurrentFolder(folder.id)}><Folder className="h-4 w-4 fill-amber-300 text-amber-500" /><span className="truncate">{folder.name}</span></button>)}</div>
        <input ref={filesRef} className="hidden" type="file" multiple onChange={(event) => void uploadFiles(event)} /><input ref={folderRef} className="hidden" type="file" multiple {...({ webkitdirectory: '' } as Record<string, string>)} onChange={(event) => void uploadFiles(event, true)} />
      </aside>
      <main className="flex min-w-0 flex-1 flex-col">
        <div className="flex items-center gap-3 border-b border-slate-200 px-5 py-3"><div className="flex min-w-0 items-center gap-1 text-sm"><button className="rounded px-2 py-1 font-medium hover:bg-slate-100" onClick={() => setCurrentFolder('')}>My Drive</button>{currentFolderName && <><ChevronRight className="h-4 w-4 text-slate-400" /><span className="truncate rounded px-2 py-1 font-medium">{currentFolderName}</span></>}</div><div className="relative ml-auto w-64"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><Input className="h-9 rounded-full bg-slate-100 pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search in project" /></div><div className="flex rounded-lg border border-slate-200 p-0.5"><button aria-label="Grid view" className={`rounded-md p-1.5 ${grid ? 'bg-brand-50 text-brand-700' : 'text-slate-500'}`} onClick={() => setGrid(true)}><Grid2X2 className="h-4 w-4" /></button><button aria-label="List view" className={`rounded-md p-1.5 ${!grid ? 'bg-brand-50 text-brand-700' : 'text-slate-500'}`} onClick={() => setGrid(false)}><List className="h-4 w-4" /></button></div></div>
        {composer && <div className="border-b border-slate-200 bg-brand-50/60 px-5 py-3">{composer === 'folder' ? <div className="flex items-end gap-2"><div className="max-w-sm flex-1"><Label>New folder</Label><Input autoFocus className="mt-1 bg-surface" value={folderName} onChange={(event) => setFolderName(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void createFolder(); }} placeholder="Untitled folder" /></div><Button disabled={saving || !folderName.trim()} onClick={() => void createFolder()}>Create</Button><Button variant="ghost" onClick={() => setComposer(null)}><X className="h-4 w-4" /></Button></div> : <div className="grid grid-cols-[1fr_1.5fr_auto_auto] items-end gap-2"><div><Label>Link name</Label><Input autoFocus className="mt-1 bg-surface" value={linkName} onChange={(event) => setLinkName(event.target.value)} placeholder="Project Google Drive" /></div><div><Label>URL</Label><Input className="mt-1 bg-surface" type="url" value={linkUrl} onChange={(event) => setLinkUrl(event.target.value)} placeholder="https://drive.google.com/…" /></div><Button disabled={saving || !linkName.trim() || !linkUrl.trim()} onClick={() => void addLink()}>Add link</Button><Button variant="ghost" onClick={() => setComposer(null)}><X className="h-4 w-4" /></Button></div>}</div>}
        <div className="min-h-0 flex-1 overflow-y-auto p-5">
          {!currentFolder && visibleFolders.length > 0 && <><p className="mb-3 text-sm font-semibold text-slate-600">Folders</p><div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-3">{visibleFolders.map((folder) => <button key={folder.id} className="group flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-left hover:border-brand-300 hover:bg-brand-50/40" onClick={() => setCurrentFolder(folder.id)}><Folder className="h-6 w-6 fill-amber-300 text-amber-500" /><span className="min-w-0 flex-1 truncate text-sm font-medium">{folder.name}</span><MoreVertical className="h-4 w-4 text-slate-400 opacity-0 group-hover:opacity-100" /></button>)}</div></>}
          {(visibleResources.length > 0 || visibleFolders.length > 0) && <p className="mb-3 text-sm font-semibold text-slate-600">Files and links</p>}
          {grid ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{visibleResources.map((resource) => <button key={resource.id} className="group overflow-hidden rounded-xl border border-slate-200 bg-surface text-left hover:border-brand-300 hover:shadow-sm" onDoubleClick={() => openResource(resource)}><div className="flex h-24 items-center justify-center bg-slate-50">{resource.type === 'link' ? <Link2 className="h-9 w-9 text-blue-500" /> : <File className="h-9 w-9 text-brand-500" />}</div><div className="flex items-center gap-2 p-3"><span className="min-w-0 flex-1 truncate text-sm font-medium">{resource.name}</span><span role="button" aria-label={`Open ${resource.name}`} className="rounded p-1 text-slate-400 hover:bg-slate-100" onClick={(event) => { event.stopPropagation(); openResource(resource); }}>{resource.type === 'link' ? <ExternalLink className="h-4 w-4" /> : <Download className="h-4 w-4" />}</span></div></button>)}</div> : <div className="overflow-hidden rounded-xl border border-slate-200"><div className="grid grid-cols-[1fr_130px_42px] border-b bg-slate-50 px-4 py-2 text-xs font-semibold text-slate-500"><span>Name</span><span>Type</span><span /></div>{visibleResources.map((resource) => <div key={resource.id} className="grid grid-cols-[1fr_130px_42px] items-center border-b px-4 py-2.5 last:border-0 hover:bg-slate-50"><span className="flex min-w-0 items-center gap-3">{resource.type === 'link' ? <Link2 className="h-5 w-5 shrink-0 text-blue-500" /> : <File className="h-5 w-5 shrink-0 text-brand-500" />}<span className="truncate text-sm font-medium">{resource.name}</span></span><span className="text-xs text-slate-500">{resource.type === 'link' ? 'External link' : resource.mimeType || 'File'}</span><button className="rounded p-1.5 hover:bg-slate-200" onClick={() => openResource(resource)}>{resource.type === 'link' ? <ExternalLink className="h-4 w-4" /> : <Download className="h-4 w-4" />}</button></div>)}</div>}
          {!visibleFolders.length && !visibleResources.length && <div className="flex h-72 flex-col items-center justify-center text-center"><FolderOpen className="mb-3 h-16 w-16 text-slate-200" /><p className="font-medium text-slate-600">{term ? 'No matching files or folders' : 'This folder is empty'}</p><p className="mt-1 text-sm text-slate-400">Use the New button to upload files, attach a folder, or add a link.</p></div>}
        </div>
      </main>
    </div>
  </Dialog>;
}
